import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Cormorant_Garamond,
  Inter,
  Space_Grotesk,
  JetBrains_Mono,
  Josefin_Sans,
  Anta,
} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/themeContext";

const garamond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${garamond.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-surface flex flex-col w-full ">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
